name: campus_events
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Firebase core + auth + firestore
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Map + URL launcher
  google_maps_flutter: ^2.6.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lint rules
  flutter_lints: ^5.0.0

flutter:
  # Include Material icons
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts, use the fonts section here.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
